- name: Ubuntu setup
  hosts: localhost
  become: yes

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        # upgrade: dist
        # not upgrade because it take long time

    - name: Install dependencies
      apt:
        name:
          - curl
          - git
          - zsh
          - gnome-tweaks
    
    - name: Remap Caps Lock to Escape
      shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"