- name: Ubuntu setup
  hosts: localhost
  become: yes

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        # upgrade: dist
        # not upgrade because it takes long time

    - name: Install dependencies
      apt:
        name:
          - git
          - gh
          - zsh
          - gnome-tweaks

    - name: Remap Caps Lock to Escape
      shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
      become: no
      # Remap Caps Lock to Escape key

    - name: Change shell to zsh
      shell: chsh -s $(which zsh)
      become: no
      
    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      become: no

      # Shortcuts:
      # Super + F: Firefox
      # Super + Enter: Terminal (gnome-terminal)
      # Super + D: Nautilus

