- name: Ubuntu setup
  hosts: localhost
  become: yes

  tasks:
    - name: Update and upgrade
      apt:
        update_cache: yes
        upgrade: dist
        # update_cache -> apt update
        # upgrade -> apt upgrade full-upgrade // yes-> -y
        # so this task is equivalent to running `sudo apt update && sudo apt upgrade -full-upgrade`
    
    - name: Remap Caps Lock to Escape (for vim) via GNOME Tweaks
      command: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
      # rempas Caps Lock to Escape, installing GNOME Tweaks is not necessary, because it is just graphical interface for gsettings
    - name: Install zsh
      apt:
        name: zsh
        state: present
        update_cache: yes
      # install zsh

    - name: Set zsh as default shell
      command: chsh -s $(which zsh)
      when: ansible_facts['shell'] != '/bin/zsh'
      # change shell to zsh if it is not already set

    - name: Install Oh My Zsh
      command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    #install oh my zsh

    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
          - wget
          - git
        state: present
        update_cache: yes
    - name: Download latest Ghostty .deb package
      shell: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/ghostty-org/ghostty/releases/latest | grep "browser_download_url.*deb" | cut -d '"' -f 4)
        wget -O /tmp/ghostty.deb "$LATEST_VERSION"
      args:
        executable: /bin/bash

    - name: Install Ghostty
      apt:
        deb: /tmp/ghostty.deb

    - name: Remove temporary .deb file
        file:
          path: /tmp/ghostty.deb
          state: absent

    - name: Copy Ghostty configuration file
      copy:
        src: files/ghostty
        dest: ~/.config/ghostty/config
        mode: '0644'
