- name: Ubuntu setup
  hosts: localhost
  become: yes

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        # upgrade: dist
        # not upgrade because it takes long time

    - name: Install dependencies
      apt:
        name:
          - curl
          - git
          - gh
          - zsh
          - gnome-tweaks

    - name: Remap Caps Lock to Escape
      shell: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
      become: no
      # Remap Caps Lock to Escape key

    - name: Change shell to zsh
      user:
        name: "{{ ansible_env.SUDO_USER | default(ansible_user_id)}}"
        shell: /usr/bin/zsh
      
    - name: Install Oh My Zsh 
      become: no
      environment:
        ZSH: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}/.oh-my-zsh"
        RUNZSH: "no"
        CHSH: "no"
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        executable: /bin/bash

